
set(SPATIALINDEX_PACKAGE_VERSION 1.8.1)
set(SPATIALINDEX_REPO_URL https://github.com/libspatialindex/libspatialindex.git)
set(SPATIALINDEX_DEPENDS REQUIRED )
set(SPATIALINDEX_FORCE_BUILD ${CI_BUILD}) 
set(SPATIALINDEX_NO_TEST ON)
set(SPATIALINDEX_OPTIONAL ON)
